[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
rsa = { version = "0.9", features = ["serde"] }
aes-gcm = "0.10.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
base64 = "0.22"
anyhow = "1.0"
bincode = "1.3" 
